version: "3.3"
services:

  db:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
    - "45432:5432"

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - db
    env_file:
      - .env
    ports:
    - "45050:5050"
  
  backend:
    image: '${DOCKER_IMAGE_BACKEND}:${TAG-latest}'
    depends_on:
      - db
    env_file:
      - .env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
    build:
      context: .
      dockerfile: Cycode.SI/Dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-false}
    ports:
    - "48080:80"
  
volumes:
  app-db-data:
